prompt Importing table ADM_ELEMENTO...
set feedback off
set define off

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '1', 'uno', 1.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '2', 'dos', 2.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '3', 'tres', 3.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '4', 'cuatro', 4.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '5', 'cinco', 5.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '6', 'seis', 6.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '7', 'siete', 7.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '8', 'ocho', 8.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '9', 'nueve', 9.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '10', 'diez', 10.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '11', 'once', 11.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '12', 'doce', 12.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '13', 'trece', 13.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '14', 'catorce', 14.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '15', 'quince', 15.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '16', 'dieciséis', 16.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '17', 'diecisiete', 17.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '18', 'dieciocho', 18.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '19', 'diecinueve', 19.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '20', 'veinte', 20.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '21', 'veintiuno', 20.10, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '22', 'veintidós', 20.20, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '23', 'veintitrés', 20.30, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '24', 'veinticuatro', 20.40, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '25', 'veinticinco', 20.50, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '26', 'veintiséis', 20.60, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '27', 'veintisiete', 20.70, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '28', 'veintiocho', 20.80, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '29', 'veintinueve', 20.90, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '30', 'treinta', 30.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '31', 'treinta y uno', 30.10, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '32', 'treinta y dos', 30.20, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '33', 'treinta y tres', 30.30, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '34', 'treinta y cuatro', 30.40, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '35', 'treinta y cinco', 30.50, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '36', 'treinta y seis', 30.60, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '37', 'treinta y siete', 30.70, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '38', 'treinta y ocho', 30.80, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '39', 'treinta y nueve', 30.90, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '40', 'cuarenta', 40.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '41', 'cuarenta y uno', 40.10, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '42', 'cuarenta y dos', 40.20, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '43', 'cuarenta y tres', 40.30, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '44', 'cuarenta y cuatro', 40.40, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '45', 'cuarenta y cinco', 40.50, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '46', 'cuarenta y seis', 40.60, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '47', 'cuarenta y siete', 40.70, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '48', 'cuarenta y ocho', 40.80, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '49', 'cuarenta y nueve', 40.90, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '50', 'cincuenta', 50.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '51', 'cincuenta y uno', 50.10, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '52', 'cincuenta y dos', 50.20, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '53', 'cincuenta y tres', 50.30, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '54', 'cincuenta y cuatro', 50.40, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '55', 'cincuenta y cinco', 50.50, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '56', 'cincuenta y seis', 50.60, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '57', 'cincuenta y siete', 50.70, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '58', 'cincuenta y ocho', 50.80, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '59', 'cincuenta y nueve', 50.90, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '60', 'sesenta', 60.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '61', 'sesenta y uno', 60.10, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '62', 'sesenta y dos', 60.20, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '63', 'sesenta y tres', 60.30, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '64', 'sesenta y cuatro', 60.40, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '65', 'sesenta y cinco', 60.50, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '66', 'sesenta y seis', 60.60, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '67', 'sesenta y siete', 60.70, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '68', 'sesenta y ocho', 60.80, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '69', 'sesenta y nueve', 60.90, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '70', 'setenta', 70.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '01', 'uno', 1.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '02', 'dos', 2.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '03', 'tres', 3.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '04', 'cuatro', 4.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '05', 'cinco', 5.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '06', 'seis', 6.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '07', 'siete', 7.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '08', 'ocho', 8.00, '1');

insert into ADM_ELEMENTO (COD_TABLA, COD_ELEMENTO, DES_ELEMENTO, NUM_SEC, IND_ACTIVO)
values ('EDU_DES_HORAS_CONSTANCIA', '09', 'nueve', 9.00, '1');

prompt Done.
